require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FastTrackPaymentsController do

  # This should return the minimal set of attributes required to create a valid
  # FastTrackPayment. As you add validations to FastTrackPayment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FastTrackPaymentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all fast_track_payments as @fast_track_payments" do
      fast_track_payment = FastTrackPayment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fast_track_payments).should eq([fast_track_payment])
    end
  end

  describe "GET show" do
    it "assigns the requested fast_track_payment as @fast_track_payment" do
      fast_track_payment = FastTrackPayment.create! valid_attributes
      get :show, {:id => fast_track_payment.to_param}, valid_session
      assigns(:fast_track_payment).should eq(fast_track_payment)
    end
  end

  describe "GET new" do
    it "assigns a new fast_track_payment as @fast_track_payment" do
      get :new, {}, valid_session
      assigns(:fast_track_payment).should be_a_new(FastTrackPayment)
    end
  end

  describe "GET edit" do
    it "assigns the requested fast_track_payment as @fast_track_payment" do
      fast_track_payment = FastTrackPayment.create! valid_attributes
      get :edit, {:id => fast_track_payment.to_param}, valid_session
      assigns(:fast_track_payment).should eq(fast_track_payment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FastTrackPayment" do
        expect {
          post :create, {:fast_track_payment => valid_attributes}, valid_session
        }.to change(FastTrackPayment, :count).by(1)
      end

      it "assigns a newly created fast_track_payment as @fast_track_payment" do
        post :create, {:fast_track_payment => valid_attributes}, valid_session
        assigns(:fast_track_payment).should be_a(FastTrackPayment)
        assigns(:fast_track_payment).should be_persisted
      end

      it "redirects to the created fast_track_payment" do
        post :create, {:fast_track_payment => valid_attributes}, valid_session
        response.should redirect_to(FastTrackPayment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fast_track_payment as @fast_track_payment" do
        # Trigger the behavior that occurs when invalid params are submitted
        FastTrackPayment.any_instance.stub(:save).and_return(false)
        post :create, {:fast_track_payment => {  }}, valid_session
        assigns(:fast_track_payment).should be_a_new(FastTrackPayment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FastTrackPayment.any_instance.stub(:save).and_return(false)
        post :create, {:fast_track_payment => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fast_track_payment" do
        fast_track_payment = FastTrackPayment.create! valid_attributes
        # Assuming there are no other fast_track_payments in the database, this
        # specifies that the FastTrackPayment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FastTrackPayment.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => fast_track_payment.to_param, :fast_track_payment => { "these" => "params" }}, valid_session
      end

      it "assigns the requested fast_track_payment as @fast_track_payment" do
        fast_track_payment = FastTrackPayment.create! valid_attributes
        put :update, {:id => fast_track_payment.to_param, :fast_track_payment => valid_attributes}, valid_session
        assigns(:fast_track_payment).should eq(fast_track_payment)
      end

      it "redirects to the fast_track_payment" do
        fast_track_payment = FastTrackPayment.create! valid_attributes
        put :update, {:id => fast_track_payment.to_param, :fast_track_payment => valid_attributes}, valid_session
        response.should redirect_to(fast_track_payment)
      end
    end

    describe "with invalid params" do
      it "assigns the fast_track_payment as @fast_track_payment" do
        fast_track_payment = FastTrackPayment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FastTrackPayment.any_instance.stub(:save).and_return(false)
        put :update, {:id => fast_track_payment.to_param, :fast_track_payment => {  }}, valid_session
        assigns(:fast_track_payment).should eq(fast_track_payment)
      end

      it "re-renders the 'edit' template" do
        fast_track_payment = FastTrackPayment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FastTrackPayment.any_instance.stub(:save).and_return(false)
        put :update, {:id => fast_track_payment.to_param, :fast_track_payment => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fast_track_payment" do
      fast_track_payment = FastTrackPayment.create! valid_attributes
      expect {
        delete :destroy, {:id => fast_track_payment.to_param}, valid_session
      }.to change(FastTrackPayment, :count).by(-1)
    end

    it "redirects to the fast_track_payments list" do
      fast_track_payment = FastTrackPayment.create! valid_attributes
      delete :destroy, {:id => fast_track_payment.to_param}, valid_session
      response.should redirect_to(fast_track_payments_url)
    end
  end

end
